// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eudtkjrfcykohtlrrvda.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1ZHRranJmY3lrb2h0bHJydmRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMDQ4MzIsImV4cCI6MjA3Mzc4MDgzMn0.4iLCwEcjwy5Kf68Ku7WjJ0CxmfGCsd-GLqEL2MHYw8A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});